# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a5a03a2d9caa2057cd8418c9b17d01eea381b147206e1ba8f3a87763288683368d8b990c2ba367368613b7cb97677bba0687286329899f581c1cf606a4440e0e

test:
  secret_key_base: b462add8962f54f1eaff6c438536412be4e3b14118626dbb6743f8a7436ef0e15ac57cc4b52177e7670e3615693218b111c820037cfe14fa3977430dd8125f15

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
